application: mathblogging
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin  
- url: /content/(.*)
  static_files: content/\1
  upload: content/(.*)
- url: /favicon.ico
  static_files: content/favicon.ico
  upload: content/favicon.ico
- url: /fetch
  script: main.py
  login: admin
- url: /allworker
  script: main.py
  login: admin
- url: /taglistworker
  script: main.py
  login: admin
- url: /clearpagecache
  script: main.py
  login: admin
- url: /reboot
  script: main.py
  login: admin
- url: .*
  script: main.py
  
builtins:
- datastore_admin: on
